# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: CGO_ENABLED=0; GOOS=linux; GOARCH=amd64; go build -ldflags='-s -w' -v ./...
